[project]
name = "rag-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.4"
dependencies = [
    "ipykernel>=6.29.5",
    "langchain-huggingface>=0.2.0",
    "langchain-ollama>=0.3.3",
]
